import type { Branch, Doctor } from "@/lib/types";
export { SESSION_META, DAYS_OF_WEEK } from "@/lib/types";
export type { SessionType, DayOfWeek, DoctorScheduleSlot, SessionConfig } from "@/lib/types";

export const branches: Branch[] = [
  {
    branchId: "BR-001",
    name: "Colombo Central Branch",
    address: "123 Galle Road, Colombo 03",
    city: "Colombo",
    phone: "+94 11 234 5678",
    email: "colombo@medsync.lk",
    managerName: "Dr. Gamini Senaratne",
    isActive: true,
  },
  {
    branchId: "BR-002",
    name: "Kandy Healthcare Facility",
    address: "45 Peradeniya Road, Kandy",
    city: "Kandy",
    phone: "+94 81 223 4567",
    email: "kandy@medsync.lk",
    managerName: "Dr. Chandra Wickrema",
    isActive: true,
  },
  {
    branchId: "BR-003",
    name: "Galle Seaside Clinic",
    address: "88 Matara Road, Galle",
    city: "Galle",
    phone: "+94 91 224 8899",
    email: "galle@medsync.lk",
    managerName: "Dr. Lalith Karunaratne",
    isActive: true,
  },
];

export const doctors: Doctor[] = [
  {
    doctorId: "DOC-001",
    name: "Dr. Sarah Jenkins",
    specialization: "Cardiology",
    branchId: "BR-001",
    branchName: "Colombo Central Branch",
    consultationFee: 3500,
    experience: 12,
    education: "MBBS, MD - Cardiology, FACC",
    bio: "Senior consultant cardiologist with over a decade of clinical experience in interventional cardiology and preventive cardiovascular health.",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 128,
    avatar: "SJ",
    phone: "+94 77 123 4567",
    email: "sarah.jenkins@medsync.lk",
  },
  {
    doctorId: "DOC-002",
    name: "Dr. Aruna Perera",
    specialization: "General Practice",
    branchId: "BR-001",
    branchName: "Colombo Central Branch",
    consultationFee: 2500,
    experience: 15,
    education: "MBBS, MD - Family Medicine",
    bio: "Experienced family physician committed to holistic preventive healthcare, routine physical exams, and chronic disease management.",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 210,
    avatar: "AP",
    phone: "+94 77 234 5678",
    email: "aruna.perera@medsync.lk",
  },
  {
    doctorId: "DOC-003",
    name: "Dr. Dilshan Jayawardena",
    specialization: "Orthopedics",
    branchId: "BR-002",
    branchName: "Kandy Healthcare Facility",
    consultationFee: 3000,
    experience: 10,
    education: "MBBS, MS - Orthopedics, FRCS",
    bio: "Specializing in sports medicine, joint replacements, and modern arthroscopic surgical procedures with patient-centered rehab.",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 95,
    avatar: "DJ",
    phone: "+94 77 345 6789",
    email: "dilshan.j@medsync.lk",
  },
  {
    doctorId: "DOC-004",
    name: "Dr. Ananya Sharma",
    specialization: "Dermatology",
    branchId: "BR-001",
    branchName: "Colombo Central Branch",
    consultationFee: 2800,
    experience: 8,
    education: "MBBS, MD - Dermatology & Venereology",
    bio: "Expert in clinical dermatology, acne treatments, eczema management, and therapeutic skincare procedures.",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 142,
    avatar: "AS",
    phone: "+94 77 456 7890",
    email: "ananya.sharma@medsync.lk",
  },
  {
    doctorId: "DOC-005",
    name: "Dr. Kasun Fernando",
    specialization: "Neurology",
    branchId: "BR-002",
    branchName: "Kandy Healthcare Facility",
    consultationFee: 4000,
    experience: 14,
    education: "MBBS, MD, DM - Neurology",
    bio: "Specialist neuro-physician focusing on migraines, stroke prevention, neurodegenerative conditions, and epilepsy management.",
    isAvailable: true,
    rating: 4.9,
    reviewCount: 88,
    avatar: "KF",
    phone: "+94 77 567 8901",
    email: "kasun.fernando@medsync.lk",
  },
  {
    doctorId: "DOC-006",
    name: "Dr. Tharushi Silva",
    specialization: "Pediatrics",
    branchId: "BR-003",
    branchName: "Galle Seaside Clinic",
    consultationFee: 2600,
    experience: 9,
    education: "MBBS, DCH, MD - Pediatrics",
    bio: "Dedicated pediatrician passionate about child development, infant nutrition, vaccinations, and pediatric emergency care.",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 160,
    avatar: "TS",
    phone: "+94 77 678 9012",
    email: "tharushi.silva@medsync.lk",
  },
  {
    doctorId: "DOC-007",
    name: "Dr. Nuwan Wickramasinghe",
    specialization: "Gynecology",
    branchId: "BR-003",
    branchName: "Galle Seaside Clinic",
    consultationFee: 3200,
    experience: 11,
    education: "MBBS, MS - Obstetrics & Gynecology",
    bio: "Compassionate specialist in women's reproductive health, antenatal care, infertility evaluations, and laparoscopic surgery.",
    isAvailable: true,
    rating: 4.7,
    reviewCount: 115,
    avatar: "NW",
    phone: "+94 77 789 0123",
    email: "nuwan.w@medsync.lk",
  },
  {
    doctorId: "DOC-008",
    name: "Dr. Priyantha Bandara",
    specialization: "Psychology",
    branchId: "BR-002",
    branchName: "Kandy Healthcare Facility",
    consultationFee: 3000,
    experience: 7,
    education: "MBBS, MD - Psychiatry, MPhil",
    bio: "Clinical psychiatrist specializing in stress management, cognitive behavioral approaches, mood disorders, and adolescent mental wellness.",
    isAvailable: false,
    rating: 4.9,
    reviewCount: 76,
    avatar: "PB",
    phone: "+94 77 890 1234",
    email: "priyantha.b@medsync.lk",
  },
  {
    doctorId: "DOC-009",
    name: "Dr. Malini Senanayake",
    specialization: "ENT",
    branchId: "BR-001",
    branchName: "Colombo Central Branch",
    consultationFee: 2900,
    experience: 13,
    education: "MBBS, MS - Otolaryngology",
    bio: "Ear, Nose, and Throat surgeon with extensive experience in sinus care, hearing disorders, voice therapies, and tonsillectomies.",
    isAvailable: true,
    rating: 4.8,
    reviewCount: 104,
    avatar: "MS",
    phone: "+94 77 901 2345",
    email: "malini.s@medsync.lk",
  },
];
export const patients: any[] = [];
export const employees: any[] = [];
export const medications: any[] = [];
export const treatmentCatalogue: any[] = [];
export const insuranceProviders: any[] = [];
export const insurancePackages: any[] = [];

// For charts
export const revenueByMonth: any[] = [];
export const appointmentsByMonth: any[] = [];
export const patientGrowthByMonth: any[] = [];

// Fallbacks for stores
export const sessionConfigs: any[] = [];
export const doctorSchedules: any[] = [];
