export interface Doctor {
  doctorId: string;
  name: string;
  specialization: string;
  branchId: string;
  branchName: string;
  email: string;
  phone: string;
  rating: number;
  reviewCount: number;
  consultationFee: number;
  experience: number; // years
  avatar: string;
  bio: string;
  education: string;
  isAvailable: boolean;
  fullyBookedDate?: string; // For demo: DOC-005 has a fully booked Monday
}

export const doctors: Doctor[] = [
  {
    doctorId: "DOC-001",
    name: "Dr. Sarah Mitchell",
    specialization: "Cardiology",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "sarah.mitchell@medsync.com",
    phone: "+1 (415) 555-1001",
    rating: 4.9,
    reviewCount: 312,
    consultationFee: 180,
    experience: 14,
    avatar: "SM",
    bio: "Board-certified cardiologist with 14 years of experience in interventional cardiology and heart failure management.",
    education: "MD, Stanford University School of Medicine",
    isAvailable: true,
  },
  {
    doctorId: "DOC-002",
    name: "Dr. Alan James",
    specialization: "General Practice",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "alan.james@medsync.com",
    phone: "+1 (415) 555-1002",
    rating: 4.7,
    reviewCount: 509,
    consultationFee: 90,
    experience: 10,
    avatar: "AJ",
    bio: "Family medicine specialist focused on preventive care, chronic disease management, and patient education.",
    education: "MD, UCSF School of Medicine",
    isAvailable: true,
  },
  {
    doctorId: "DOC-003",
    name: "Dr. Yashfin Jhosof",
    specialization: "Cardiology",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "yashfin.jhosof@medsync.com",
    phone: "+1 (415) 555-1003",
    rating: 4.8,
    reviewCount: 209,
    consultationFee: 200,
    experience: 18,
    avatar: "YJ",
    bio: "Senior cardiologist specializing in cardiac imaging and electrophysiology procedures.",
    education: "MD, Harvard Medical School",
    isAvailable: true,
  },
  {
    doctorId: "DOC-004",
    name: "Dr. Toshid Khomsi",
    specialization: "Dermatology",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "toshid.khomsi@medsync.com",
    phone: "+1 (415) 555-1004",
    rating: 4.6,
    reviewCount: 178,
    consultationFee: 150,
    experience: 9,
    avatar: "TK",
    bio: "Dermatologist specializing in acne, eczema, psoriasis, and cosmetic dermatology.",
    education: "MD, Johns Hopkins University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-005",
    name: "Dr. Emily Carter",
    specialization: "Neurology",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "emily.carter@medsync.com",
    phone: "+1 (510) 555-1005",
    rating: 4.8,
    reviewCount: 267,
    consultationFee: 210,
    experience: 12,
    avatar: "EC",
    // DOC-005 has all Monday slots fully booked — demo edge case
    fullyBookedDate: "2026-07-28",
    bio: "Neurologist specializing in epilepsy, migraine, and neurodegenerative diseases.",
    education: "MD, Yale School of Medicine",
    isAvailable: true,
  },
  {
    doctorId: "DOC-006",
    name: "Dr. David Wilson",
    specialization: "Pediatrics",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "david.wilson@medsync.com",
    phone: "+1 (510) 555-1006",
    rating: 4.9,
    reviewCount: 421,
    consultationFee: 120,
    experience: 16,
    avatar: "DW",
    bio: "Pediatrician with special interest in childhood development, immunizations, and respiratory conditions.",
    education: "MD, Columbia University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-007",
    name: "Dr. Sophia Adams",
    specialization: "Gynecology",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "sophia.adams@medsync.com",
    phone: "+1 (510) 555-1007",
    rating: 4.7,
    reviewCount: 293,
    consultationFee: 160,
    experience: 11,
    avatar: "SA",
    bio: "Gynecologist and obstetrician specializing in high-risk pregnancies and minimally invasive surgery.",
    education: "MD, Duke University School of Medicine",
    isAvailable: true,
  },
  {
    doctorId: "DOC-008",
    name: "Dr. James Clark",
    specialization: "Dermatology",
    branchId: "BR-003",
    branchName: "MedSync South Bay",
    email: "james.clark@medsync.com",
    phone: "+1 (408) 555-1008",
    rating: 4.5,
    reviewCount: 145,
    consultationFee: 140,
    experience: 7,
    avatar: "JC",
    bio: "Dermatologist focused on skin cancer screening, mole mapping, and advanced laser treatments.",
    education: "MD, University of Michigan",
    isAvailable: true,
  },
  {
    doctorId: "DOC-009",
    name: "Dr. Rachel Park",
    specialization: "Orthopedics",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "rachel.park@medsync.com",
    phone: "+1 (415) 555-1009",
    rating: 4.8,
    reviewCount: 332,
    consultationFee: 190,
    experience: 13,
    avatar: "RP",
    bio: "Orthopedic surgeon specializing in joint replacement, sports injuries, and spine conditions.",
    education: "MD, University of Pennsylvania",
    isAvailable: true,
  },
  {
    doctorId: "DOC-010",
    name: "Dr. Marcus Williams",
    specialization: "Psychology",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "marcus.williams@medsync.com",
    phone: "+1 (415) 555-1010",
    rating: 4.9,
    reviewCount: 198,
    consultationFee: 170,
    experience: 15,
    avatar: "MW",
    bio: "Clinical psychologist specializing in anxiety, depression, PTSD, and cognitive behavioral therapy.",
    education: "PhD, UCLA Department of Psychology",
    isAvailable: true,
  },
  {
    doctorId: "DOC-011",
    name: "Dr. Patricia Lee",
    specialization: "General Practice",
    branchId: "BR-003",
    branchName: "MedSync South Bay",
    email: "patricia.lee@medsync.com",
    phone: "+1 (408) 555-1011",
    rating: 4.6,
    reviewCount: 287,
    consultationFee: 85,
    experience: 8,
    avatar: "PL",
    bio: "Family physician with expertise in geriatric care, diabetes management, and preventive medicine.",
    education: "MD, University of California, Davis",
    isAvailable: true,
  },
  {
    doctorId: "DOC-012",
    name: "Dr. Benjamin Hall",
    specialization: "Cardiology",
    branchId: "BR-003",
    branchName: "MedSync South Bay",
    email: "benjamin.hall@medsync.com",
    phone: "+1 (408) 555-1012",
    rating: 4.7,
    reviewCount: 241,
    consultationFee: 175,
    experience: 11,
    avatar: "BH",
    bio: "Cardiologist with expertise in echocardiography, cardiac stress testing, and prevention.",
    education: "MD, Vanderbilt University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-013",
    name: "Dr. Natasha Ivanova",
    specialization: "Neurology",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "natasha.ivanova@medsync.com",
    phone: "+1 (510) 555-1013",
    rating: 4.8,
    reviewCount: 176,
    consultationFee: 195,
    experience: 10,
    avatar: "NI",
    bio: "Neurologist specializing in stroke prevention, multiple sclerosis, and headache disorders.",
    education: "MD, Moscow State Medical University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-014",
    name: "Dr. Omar Hassan",
    specialization: "Orthopedics",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "omar.hassan@medsync.com",
    phone: "+1 (510) 555-1014",
    rating: 4.6,
    reviewCount: 208,
    consultationFee: 185,
    experience: 9,
    avatar: "OH",
    bio: "Orthopedic specialist in trauma surgery, ACL reconstruction, and rotator cuff repair.",
    education: "MD, Cairo University Faculty of Medicine",
    isAvailable: true,
  },
  {
    doctorId: "DOC-015",
    name: "Dr. Elena Rossi",
    specialization: "Pediatrics",
    branchId: "BR-003",
    branchName: "MedSync South Bay",
    email: "elena.rossi@medsync.com",
    phone: "+1 (408) 555-1015",
    rating: 4.9,
    reviewCount: 374,
    consultationFee: 110,
    experience: 14,
    avatar: "ER",
    bio: "Pediatrician specializing in neonatology, childhood nutrition, and developmental pediatrics.",
    education: "MD, University of Bologna",
    isAvailable: true,
  },
  {
    doctorId: "DOC-016",
    name: "Dr. Andre Dupont",
    specialization: "Gynecology",
    branchId: "BR-001",
    branchName: "MedSync Central",
    email: "andre.dupont@medsync.com",
    phone: "+1 (415) 555-1016",
    rating: 4.5,
    reviewCount: 162,
    consultationFee: 155,
    experience: 8,
    avatar: "AD",
    bio: "Gynecologist specializing in reproductive endocrinology, fertility treatments, and laparoscopy.",
    education: "MD, Sorbonne University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-017",
    name: "Dr. Mei Chen",
    specialization: "General Practice",
    branchId: "BR-002",
    branchName: "MedSync Westside",
    email: "mei.chen@medsync.com",
    phone: "+1 (510) 555-1017",
    rating: 4.7,
    reviewCount: 319,
    consultationFee: 95,
    experience: 12,
    avatar: "MC",
    bio: "Family medicine specialist with expertise in travel medicine, nutrition, and chronic disease management.",
    education: "MD, National Taiwan University",
    isAvailable: true,
  },
  {
    doctorId: "DOC-018",
    name: "Dr. Samuel Adeyemi",
    specialization: "Psychology",
    branchId: "BR-003",
    branchName: "MedSync South Bay",
    email: "samuel.adeyemi@medsync.com",
    phone: "+1 (408) 555-1018",
    rating: 4.8,
    reviewCount: 143,
    consultationFee: 165,
    experience: 7,
    avatar: "SA2",
    bio: "Clinical psychologist focusing on CBT, mindfulness-based therapy, and trauma recovery.",
    education: "PhD, University of Lagos",
    isAvailable: true,
  },
];
